### ISSUE TITLE
Cannot set property onunhandledrejection of [object Object] which has only a getter

### ISSUE THREAD

**Issue by patelnav** [GoogleCloudPlatform/stackdriver-errors-js#63]
This may have birthed from [Issue#35](https://github.com/GoogleCloudPlatform/stackdriver-errors-js/issues/35).

I'm seeing logs with the following error:
```
TypeError: Cannot set property onunhandledrejection of [object Object] which has only a getter
    at onunhandledrejection (../node_modules/stackdriver-errors-js/stackdriver-errors.js:91:0)
    at window.addEventListener (index.js:133:15)
```

This is happening on my starting the ErrorReporter. index.js:133 is line 3:
```
window.addEventListener('DOMContentLoaded', function () {
  var errorHandler = new StackdriverErrorReporter();
  errorHandler.start({
    targetUrl: '<my_url>',
  });
})
```

**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by steren** [comment]
Thanks for the report. Do you confirm you are using the module at HEAD?

**Comment by patelnav** [comment]
I did a bit of digging. It seems I was rejecting a promise with a string, which caused [this section](https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/stackdriver-errors.js#L118) to generate an error to report. So the stack starts at this point. 

Unfortunately the stack traces cross async-boundaries on these Promises, so they not particularly useful. 

Unless you guys can figure out how to get the full stacktrace, perhaps it would be more useful to not have a StackTrace rather than a partial & internal one.

**Comment by steren** [comment]
Version `0.5.0` is supposed to work.

Would you be able to provide a minimal sample (e.g. on codepen) that reproduces the issue?

**Comment by patelnav** [comment]
hmmm. was trying this, ran into another issue.
The CDN ( https://cdn.jsdelivr.net/npm/stackdriver-errors-js@0.5.0/dist/ ) doesn't even have a window.onunhandledrejection

A messup on publishing to CDN?
